### ISSUE TITLE
【708-week 02】暴力解法

### ISSUE THREAD

**Issue by voiddme** [algorithm004-03/algorithm004-03#506]
开始觉得暴力解法很重要，它值得你动手去写并理解里面的细节

它可以帮助你：提高编码能力、提高对题目的本质理解

很多题目有套路，比如 BSF 用队列、DFS 用栈，但也有很多题目，讲究一个循序渐进，循序渐进的第一步就是暴力解法，如果能做出并理解，优化应该也是分分钟的事，不同点在于它提供了一个思路，一个走向优化解法的思路

后面刷题可能会遵循这样一个方式，除非做过并且熟悉的题目，否则暴力求解（写出来），并一步步推导

**Comment by northleafup** [comment]
我也有这种感受，暴力解法是对一个问题第一想到的答案，当然可能也是最复杂的方案，但我同时认为，也考虑了对一个问题最原始的思考路径。
